### PR TITLE
check default newsboat dotdir

### PR DESCRIPTION
**Pull request by derjoachim**
As per the final comment of [PR 35](https://github.com/graysky2/profile-cleaner/pull/35) and the [official docs](https://newsboat.org/releases/2.25/docs/newsboat.html#_files), the script will now check the default `.newsboat` directory first, before looking in `$XDG_DATA_HOME`. Apparently, I migrated to the latter at some point in the past.

### CODE REVIEW

**Review by graysky2 — APPROVED** [review]
That'll do nicely

**Comment by Minoru** [comment]
Hi, Newsboat maintainer here :wave: You got the priorities wrong: Newsboat uses XDG if it exists, and falls back to a dotdir otherwise.

If user has both the dotdir and XDG dirs (e.g. because they migrated by copying the files), Newsboat will use XDG but this script will try to clean the dotdir. You probably want to flip the branches of the `if` here.

**Comment by graysky2** [comment]
@Minoru - Thanks for the feedback, how do https://github.com/graysky2/profile-cleaner/commit/0896be26049e562560e72b53d7f4d15d5358f578 look?

**Comment by Minoru** [comment]
That should work, @graysky2 :+1:

**Pull request merged**
